version: '3.1'

services:
  postgresql:
    image: postgres
    container_name: pgsql
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: calendar
    ports:
      - 5435:5432
  application:
    container_name: app
    image: springboot
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/calendar
    ports:
      - 9090:9090
    depends_on:
      - postgresql