server:
  port: 9090

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jooq:
    sql-dialect: postgres
    level:
      org:
        jooq: debug

jwt:
  token:
    secret: laskcnljgi0309euweo12er931ulaskcnljwi0309euweo12er931ulaskcnljwi0309euweo12er931ulaskcnljwi0309euweo12er931u
    expired: 3600000
